In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [3]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
#create tensor
string_tensor= tf.Variable("I am Rahma", tf.string)
int_tensor= tf.Variable([[123, 842]], tf.int16)
float_tensor= tf.Variable([3.456], tf.float64)

In [5]:
tf.rank(string_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
tf.rank(float_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
tf.rank(int_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [8]:
int_tensor.shape

TensorShape([1, 2])

In [9]:
#changing shape
t1=tf.ones([1,2,3])
t2 = tf.reshape(t1, [2,3,1])
t3 = tf.reshape(t2, [3, -1])

In [10]:
print(t1)
print(t2)
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [17]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor= tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [18]:
third_element=tensor[0,2]
print(third_element)

tf.Tensor(3, shape=(), dtype=int32)


In [19]:
row1=tensor[0]
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [20]:
column1=tensor[:, 0]
print(column1)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [21]:
row_2_and_4 = tensor[1::2]
print(row_2_and_4)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [22]:
column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)
